Dsv_Project_v3/Pages/Booking.cshtml.cs
using Dsv_Project_v3.Models;
using Dsv_Project_v3.Repo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using Dsv_Project_v3.Services;

namespace Dsv_Project_v3.Pages
{
    public class BookingModel : PageModel
    {
        private BookingService _bookingService;
        [BindProperty]
        public MeetingRoomBooking MeetingRoomBooking { get; set; }
        public int Lokale { get; set; }

        public BookingModel(BookingService bs)
        {
            MeetingRoomBooking = new MeetingRoomBooking();
            _bookingService = bs;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            Debug.WriteLine("test " + MeetingRoomBooking.ID);
            _bookingService.Add(MeetingRoomBooking);
            return RedirectToPage("/BookingsEditor");
        }
    }
}

Dsv_Project_v3/Pages/BookingsEditor.cshtml.cs
using Dsv_Project_v3.Models;
using Dsv_Project_v3.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Dsv_Project_v3.Pages
{
    public class BookingsEditorModel : PageModel
    {
        private readonly RoomServices _rs;
        private readonly BookingService _bs;
        [BindProperty]
        public List<MeetingRoom> Rooms { get; set; }
        public List<MeetingRoomBooking> Bookings { get; set; }

        public BookingsEditorModel(BookingService bs, RoomServices rs)
        {
            Bookings = bs.GetAll();
            Rooms = rs.GetAll();
            _bs = bs;
            _rs = rs;
        }
        public void OnGet()
        {
        }

        //method for deleting bookings
        public IActionResult OnPostDeleteBooking(int bookingId)
        {
            // Call the service to delete the booking
            _bs.DeleteBooking(bookingId);

            // Redirect back to the page to refresh the list of bookings
            return RedirectToPage();
        }

        //method for editing bookings
        public IActionResult OnPostEditBooking(int bookingId, DateTime startDateTime, DateTime endDateTime, string comment)
        {
            // Find the booking by ID
            Debug.WriteLine(bookingId);
            var bookingToUpdate = Bookings.FirstOrDefault(b => b.ID == bookingId);

            if (bookingToUpdate != null)
            {
                // Replace the old booking with the updated one
                bookingToUpdate.StartDateTime = startDateTime;
                bookingToUpdate.EndDateTime = endDateTime;
                bookingToUpdate.Comment = comment;
            }

            // Save changes to the repository or perform other necessary actions
            _bs.UpdateBooking(bookingToUpdate);

            // Redirect back to the page to refresh the list
            return RedirectToPage();
        }
    }
}

Dsv_Project_v3/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dsv_Project_v3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Dsv_Project_v3/Pages/Index.cshtml.cs
using Dsv_Project_v3.Models;
using Dsv_Project_v3.Repo;
using Dsv_Project_v3.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dsv_Project_v3.Pages
{
    public class IndexModel : PageModel
    {
        private MeetingRoom[] _meetingRoom = new MeetingRoom[6];
        IBookingRepo RoomRepo = new BookingCollectionRepo();

        private readonly RoomServices _rs;
        private readonly BookingService _bs;
        [BindProperty]
        public List<MeetingRoom> Rooms { get; set; }

        public List<MeetingRoomBooking> Bookings { get; set; }
        List<MeetingRoomBooking> _activeBookings = new List<MeetingRoomBooking>();

        bool _isBooked = false;
        [BindProperty]
        public int filterCap { get; set; }
        [BindProperty]
        public bool filterTavle { get; set; } 
        [BindProperty]
        public bool filterProjecter { get; set; }
        [BindProperty]
        public bool filterKM { get; set; }

        private DateTime setDate = DateTime.Now;

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, RoomServices rs, BookingService bs)
        {
            _logger = logger;
            Rooms = rs.GetAll();
            _rs = rs;
            Bookings = bs.GetAll();
            _bs = bs;
        }

        public void Vacancy()
        {
            foreach (MeetingRoomBooking booking in Bookings)
            {
                if (booking.StartDateTime.Date == setDate.Date)
                {
                    _activeBookings.Add(booking);
                }
            }
        }

        public bool BookChecker(int hour, int roomID)
        {
            if (_activeBookings != null)
            {
                foreach (var booking in _activeBookings)
                {
                    if (hour == booking.StartDateTime.Hour && roomID == booking.RoomID)
                    {
                        _isBooked = true;
                    }
                    else if (hour == booking.EndDateTime.Hour && roomID == booking.RoomID)
                    {
                        _isBooked = false;
                    }
                }
            }
            return _isBooked;
        }

        public void OnGet()
        {
            Vacancy();
        }

        public IActionResult OnPost(int idroom)
        {
            MeetingRoom bound = _rs.Get(idroom);

            return RedirectToPage("/Booking", new { roomname = bound.ID });
        }
    }
}

Dsv_Project_v3/Pages/Booking.cshtml
@page
@model Dsv_Project_v3.Pages.BookingModel
@{
}
<body>
    <container-sm>
        <div class="text-center">
            <h1>Book lokale</h1>
            <p>Du kan booke lokalet mellem 7:00-17:00</p>
        </div>

        <div class="card shadow-sm">
            <div class="card-body text-center">
                <form method="post">
                    <div class="form-group">
                        <label for="inputDateTime"></label>
                        <input type="datetime-local" asp-for="MeetingRoomBooking.StartDateTime" id="inputForm" aria-describedby="dateTimeHelp" placeholder="Enter Date/Time" step="3600">
                        <input type="datetime-local" asp-for="MeetingRoomBooking.EndDateTime" id="inputForm" aria-describedby="dateTimeHelp" placeholder="Enter end time" step="3600" />
                    </div>
                    <div class="form-group mt-2">
                        <select asp-for="MeetingRoomBooking.RoomID" id="Lokale">
                            <option value="0">Select a room</option>
                            <option value="1">Alpha</option>
                            <option value="2">Beta</option>
                            <option value="3">Delta</option>
                            <option value="4">Gamma</option>
                            <option value="5">Sigma</option>
                            <option value="6">Mu</option>
                        </select>
                        <label for="inputComment"></label>
                        <input type="text" asp-for="MeetingRoomBooking.Comment" id="inputForm" aria-describedby="textHelp" placeholder="Enter a comment" value="">
                        <small id="commentHelp" class="form-text text-muted mt-5">Enter any comments or special requests for the staff here.  </small>
                    </div>
                    <button type="submit" class="btn btn-primary mt-5">Submit</button>
                </form>
                </<div>
                </div>
    </container-sm>
    <script>

           var rooms=document.getElementById("Lokale");
              rooms.value=getQueryParameter("roomname");



        function getQueryParameter(name) {

             const urlParams = new URLSearchParams(window.location.search);

             return urlParams.get(name);

           }


    </script>
</body>

Dsv_Project_v3/Pages/BookingsEditor.cshtml
@page
@model Dsv_Project_v3.Pages.BookingsEditorModel
@{
}
<body>
    <div class="container row row-cols-3">
        @foreach (var booking in Model.Bookings)
        {
            var room = Model.Rooms.FirstOrDefault(r => r.ID == booking.RoomID);
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <h5 class="card-text"><b>@room?.Name</b></h5>
                        <p class="card-text">@booking.StartDateTime.ToString("ddd") - @booking.StartDateTime.ToString("dd/MM-yyyy")</p>
                        <p class="card-text">@booking.StartDateTime.ToString("HH:mm") - @booking.EndDateTime.ToString("HH:mm")</p>
                        <p class="card-text">@booking.Comment</p>

                        <div class="d-flex justify-content-end gap-3">
                            <!--button to open module for editing booking-->
                            <button class="btn btn-outline-primary EditBTN mt-1" data-bs-toggle="modal" data-bs-target="#editBookingModal"
                                    data-booking-id="@booking.ID"
                                    data-booking-start="@booking.StartDateTime"
                                    data-booking-end="@booking.EndDateTime"
                                    data-booking-comment="@booking.Comment">
                                <i class="bi bi-pencil"></i> Edit
                            </button>
                            <!--button for deleting booking-->
                            <form method="post" asp-page-handler="DeleteBooking" class="d-inline">
                                <input type="hidden" name="bookingId" value="@booking.ID" />
                                <button type="submit" class="btn btn-delete mt-1">
                                    <i class="bi bi-trash"></i> Delete
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        }

        <!--Module for editing bookings-->
        <div class="modal fade" id="editBookingModal" tabindex="-1" aria-labelledby="editBookingModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editBookingModalLabel">Edit Booking</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="post" asp-page-handler="EditBooking">
                        <div class="modal-body">
                            <input type="hidden" id="BookingId" name="BookingId" value="" />

                            <div class="mb-3">
                                <label for="StartDateTime" class="form-label">Start Date/Time</label>
                                <input type="datetime-local" class="form-control" id="StartDateTime" name="StartDateTime" required />
                            </div>

                            <div class="mb-3">
                                <label for="EndDateTime" class="form-label">End Date/Time</label>
                                <input type="datetime-local" class="form-control" id="EndDateTime" name="EndDateTime" required />
                            </div>

                            <div class="mb-3">
                                <label for="Comment" class="form-label">Comment</label>
                                <textarea class="form-control" id="Comment" name="Comment" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        var buttons = document.querySelectorAll(".EditBTN");

        buttons.forEach(function(button) {

          button.addEventListener("click", function(event) {

              var clickedButton = event.target;
        document.getElementById("BookingId").value=clickedButton.getAttribute("data-booking-id");

          });

        });
    </script>
</body>

Dsv_Project_v3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "";
}

<header class="container-fluid bg-light">
    <h3 style="font-weight: bold; color: #192862">Filtrering</h3>
    <form method="post" asp-page-handler="Filter" name="Filter" id="Filter">
        <label for="filterTavle" class="control-label">Tavle: </label>
        <input class="me-4" asp-for="filterTavle" type="checkbox" id="tavle" name="filterTavle" value="true">
        <label for="filterProjecter" class="control-label">Projecter: </label>
        <input class="me-4" asp-for="filterProjecter" type="checkbox" id="projecter" name="filterProjecter" value="true">
        <label for="filterKM" class="control-label">Kaffemaskine: </label>
        <input class="me-4" asp-for="filterKM" type="checkbox" id="kaffemaskine" name="filterKM" value="true">
        <label for="filterCap" class="control-label">Antal deltagere: </label>
        <input class="" asp-for="filterCap" type="number" id="capacity" name="filterCap" value="0" />
        <button type="submit" class="btn btn-primary">Filtrér</button>
    </form>
</header>

<div class="container">
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th>Lokale</th>
                <th>Kapacitet</th>
                <th>Tavle</th>
                <th>Projektor</th>
                <th>Kaffemaskine</th>
                <th>Tidsrum</th>
                <th>Handling</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var room in Model.Rooms)
            {
                <tr>
                    <td><b>@room.Name</b></td>
                    <td>@room.Capacity personer</td>
                    <td>@(room.Tavle ? "+" : "-")</td>
                    <td>@(room.Projecter ? "+" : "-")</td>
                    <td>@(room.Kaffemaskine ? "+" : "-")</td>
                    <td>
                        @for (int i = 6; i < 18; i++)
                        {
                            var bgColor = Model.BookChecker(i, room.ID) ? "color: red;" : "color: green;";
                            <span style="@bgColor">@i:00-@i:59</span>

                            <br />
                        }
                    </td>
                    <td>
                        <form method="post">
                            <input type="hidden" value="@room.ID" name="idroom" />
                            <button class="btn btn-outline-primary" title="Book">Book room</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
 